CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    FIRSTNAME VARCHAR NOT NULL,
    LASTNAME VARCHAR NOT NULL,
    USER_NAME VARCHAR NOT NULL UNIQUE,
    PASSWORD VARCHAR NOT NULL UNIQUE,
    EMAIL VARCHAR NOT NULL UNIQUE
);